version: '3.8'

services:
  mongo:
    build:
      context: .
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: localhost
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
